Compatibility fix with ember-cli-babel.
It turns out that asciidoctor.js >= 1.5.3 is fundamentally incompatible with
Babel. By fixing the asciidoctor.js version at 1.5.2, we get rid of the
following error on rebuild:

Cannot set property remoteAddress of #<Socket> which has only a getter
TypeError: Cannot set property remoteAddress of #<Socket> which has only a getter
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:16)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)