Fix compatibility with ember-cli-babel 5.1.6.
Apparently, ember-cli-babel will attempt to clone the object returned by the
filter constructor. Since the asciidoctor and the asciidoctor processor objects
are not clone-able, we get the following error upon build:

Cannot set property remoteAddress of #<Socket> which has only a getter
TypeError: Cannot set property remoteAddress of #<Socket> which has only a getter
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:16)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/chuan/Projects/amoya/client/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)

The solution is to defer the creation of asciidoctor objects until the first
call to processString.